add top-button
infoshareacademy/jfdz6-gorillaz pull request #1
Opened 2017-08-06 11:57 UTC by piotrkramarz

sprawdźcie proszę czy działa jak należy - top-button

2017-08-07 05:57 UTC, wojtrawi requested changes
In general, the button overlaps important features on the web page, for example some social media links are impossible to be clicked. Consider adding indicator on bottom of each section appearing when section is visible.

HTML remarks:
- please follow html naming convention: '-' separated class names and id,
- do not place event listeners in HTML code (onclick),
- add event listeners in JS code (this separate skeleton - HTML from web behaviour - JS).

CSS remarks:
- avoid articles in comments (telegraph style),
- avoid comments on trival properties like " color: white; /* Text color */".

JS remarks:
- use jQuery (provides facade for common methods and ensures cross-browsers compatibility without redundant user code),
- when targetting DOM element in JS always make sure it has already been rendered: place code inside $(document).ready(function(){});

2017-08-08 08:13 UTC, wojtrawi approved these changes

2017-08-08 15:09 UTC, Czapelxd commented
Kk

2017-08-08 15:10 UTC, Czapelxd commented
Z poziomu telefonu nie mam jak zaakceptować

2017-08-08 15:11 UTC, merged